services:
  async_fastapi_multi:
    container_name: async_fastapi_multi
    image: async_fastapi_multi_image
    env_file:
      - .env

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./:/src

    ports:
      - "16000:8006"

    depends_on:  # Make sure that async_fastapi_multi_mysql starts first by depending on it.
      - async_fastapi_multi_mysql

  async_fastapi_multi_mysql:  # mysql server
    container_name: async_fastapi_multi_mysql
    hostname: async_fastapi_multi_mysql
    image: mysql:9.0
    env_file:
      - .env

    volumes:
      - async_fastapi_multi_mysql_data:/var/lib/mysql
      - async_fastapi_multi_mysql_data_backups:/backups
      # - ./scripts/mysql:/scripts

    command:
      - --character-set-server=utf8mb4  # Set the database character set to utf8mb4.
      - --collation-server=utf8mb4_general_ci  # Set the collation to utf8mb4_general_ci.

    ports:
      - "33306:3306"

  async_fastapi_multi_redis:  # redis config.
    image: redis:6.2-alpine
    hostname: redis
    container_name: async_fastapi_multi_redis

    env_file:
      - .env

    volumes:
      - async_fastapi_multi_redis_data:/var/lib/redis

    command:
      - 'redis-server'  # start redis server.
      - '--requirepass 123456'  # set redis password.

    ports:
      - "36379:6379"  # Map the host's port 36379 to the container's port 6379.

volumes:  # data persistence.
  async_fastapi_multi_mysql_data:
    driver: "local"

  async_fastapi_multi_mysql_data_backups:
    driver: "local"

  async_fastapi_multi_redis_data:
    driver: "local"

networks:
  default:
    external: true
    name: async_fastapi_multi_network  # network name.